
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SKG
 */
public class _Grup_27_Anasayfa extends javax.swing.JFrame {

    _Grup_27_Methods mtd = new _Grup_27_Methods();
    _Grup_27_Command commands = new _Grup_27_Command();

    /**
     * Creates new form _Grup_27_Anasayfa
     */
    public _Grup_27_Anasayfa() {
        initComponents();
        lblAC.setText(_Grup_27_Command.AC);
        lblPC.setText(_Grup_27_Command.PC);
        lblAR.setText(_Grup_27_Command.AR);
        lblDR.setText(_Grup_27_Command.DR);
        lblIR.setText(_Grup_27_Command.IR);

        // _Grup_27_RunSymbol.runSymbol("010000000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAssamblyCode = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taHexCode = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnDerle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMemory = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taLabelTable = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnCalistir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taSymbolCode = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taBinaryCode = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPC = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAR = new javax.swing.JLabel();
        lblDR = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        taMicroTable = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblIR = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taAssamblyCode.setEditable(false);
        taAssamblyCode.setColumns(20);
        taAssamblyCode.setRows(5);
        jScrollPane1.setViewportView(taAssamblyCode);

        jLabel1.setText("Assambly Code");

        taHexCode.setEditable(false);
        taHexCode.setColumns(20);
        taHexCode.setRows(5);
        jScrollPane2.setViewportView(taHexCode);

        jLabel2.setText("Symbol Code");

        btnDerle.setText("DERLE");
        btnDerle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerleActionPerformed(evt);
            }
        });

        tblMemory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0000", "0", "0000", "0000"},
                {"0001", "0", "0000", "0000"},
                {"0010", "0", "0000", "0000"},
                {"0011", "0", "0000", "0000"},
                {"0100", "0", "0000", "0000"},
                {"0101", "0", "0000", "0000"},
                {"0110", "0", "0000", "0000"},
                {"0111", "0", "0000", "0000"},
                {"1000", "0", "0000", "0000"},
                {"1001", "0", "0000", "0000"},
                {"1010", "0", "0000", "0000"},
                {"1011", "0", "0000", "0000"},
                {"1100", "0", "0000", "0000"},
                {"1101", "0", "0000", "0000"},
                {"1110", "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"},
                {null, "0", "0000", "0000"}
            },
            new String [] {
                "Adress", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblMemory);

        jLabel3.setText("Memory");

        taLabelTable.setEditable(false);
        taLabelTable.setColumns(20);
        taLabelTable.setRows(5);
        jScrollPane4.setViewportView(taLabelTable);

        jLabel4.setText("Label Table");

        btnCalistir.setText("ÇALIŞTIR");
        btnCalistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalistirActionPerformed(evt);
            }
        });

        jLabel5.setText("AC  :");

        taSymbolCode.setEditable(false);
        taSymbolCode.setColumns(20);
        taSymbolCode.setRows(5);
        jScrollPane5.setViewportView(taSymbolCode);

        jLabel7.setText("Hex Code");

        taBinaryCode.setEditable(false);
        taBinaryCode.setColumns(20);
        taBinaryCode.setRows(5);
        jScrollPane6.setViewportView(taBinaryCode);

        jLabel8.setText("Binary Code");

        jLabel9.setText("PC  :");

        lblPC.setOpaque(true);

        jLabel10.setText("DR  :");

        jLabel6.setText("AR  :");

        lblDR.setOpaque(true);

        taMicroTable.setEditable(false);
        taMicroTable.setColumns(20);
        taMicroTable.setRows(5);
        jScrollPane7.setViewportView(taMicroTable);

        jLabel11.setText("Micro Table");

        jLabel12.setText("IR   :");

        lblIR.setOpaque(true);

        jLabel13.setText("Output");

        taOutput.setEditable(false);
        taOutput.setColumns(20);
        taOutput.setRows(5);
        taOutput.setEnabled(false);
        jScrollPane8.setViewportView(taOutput);

        jMenu1.setText("File");

        jMenuItem1.setText("Dosya Yükle");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Çıktı Al(.mif)");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblAC))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblPC))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel6))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addComponent(lblAR))
                                                    .addComponent(lblDR)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblIR))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDerle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCalistir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(7, 7, 7)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(btnDerle)
                                                    .addComponent(btnCalistir))
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(lblAC))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel9)
                                                    .addComponent(lblPC))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel10))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblAR)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblDR)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(lblIR)))
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static public ArrayList<String[]> code = new ArrayList();
    static public ArrayList<String[]> symbolCode = new ArrayList();
    static public ArrayList<String[]> hexCode = new ArrayList();
    static public ArrayList<String[]> binaryCode = new ArrayList();

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jFileChooser1.showOpenDialog(this);
        File f = jFileChooser1.getSelectedFile();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(f));
            String line = null;
            while (reader.ready()) {
                line = reader.readLine();
                if (line.charAt(0) != '\u0000' && line.charAt(0) != '/') {
                    taAssamblyCode.append(line + "\n");
                    String[] lineSplit = line.split(" ");
                    if (lineSplit[0].contains("ORG")) {
                        int temp = Integer.parseInt(lineSplit[1]);
                        _Grup_27_Command.PC = Integer.toBinaryString(temp);
                        int temp2 = _Grup_27_Command.PC.length();
                        for (int i = 0; i < 4 - temp2; i++) {
                            _Grup_27_Command.PC = "0" + _Grup_27_Command.PC;
                        }
                        lblPC.setText(_Grup_27_Command.PC);
                        lblPC.setBackground(Color.pink);
                    }
                    code.add(lineSplit);
                }
            }
            reader.close();
        } catch (Exception ex) {
            System.err.println(ex);
        }

        int startAdress = Integer.parseInt(code.get(0)[1]);
        String lineOpCode = null;
        for (int i = 1; i < code.size() - 1; i++) {
            String addAdress = mtd.getAdressFormat(String.valueOf(startAdress));
            String[] lineCode = code.get(i);
            if (lineCode[0].charAt(lineCode[0].length() - 1) == ',') {
                if (lineCode[1].charAt(0) == 'D') {
                    lineOpCode = mtd.convertDecToHex(lineCode[2]);
                } else {
                    lineOpCode = lineCode[2];
                }
            } else {
                lineOpCode = lineCode[0];
            }
            String[] symbolCodeLine = {addAdress + startAdress, lineOpCode, ""};

            symbolCode.add(symbolCodeLine);
            startAdress++;
        }

        for (int i = 1; i < code.size(); i++) {
            if (code.get(i)[0].charAt(code.get(i)[0].length() - 1) == ',') {
                taLabelTable.append(code.get(i)[0] + " " + code.get(i)[2] + "\n");
                for (int j = 1; j < code.size(); j++) {
                    if (code.get(j)[0].charAt(code.get(j)[0].length() - 1) != ',') {
                        if (code.get(j).length > 1) {
                            if (code.get(i)[0].charAt(0) == code.get(j)[1].charAt(0)) {
                                symbolCode.get(j - 1)[2] = symbolCode.get(i - 1)[0];
                            }
                        }
                    }
                }
            }
        }

        String hexConvert = null;
        for (int i = 0; i < symbolCode.size(); i++) {
            String[] lineCode = code.get(i + 1);
            if (lineCode[0].charAt(lineCode[0].length() - 1) == ',') {

                hexConvert = symbolCode.get(i)[1];
            } else {
                hexConvert = commands.getHexCodeValue(symbolCode.get(i)[1]) + symbolCode.get(i)[2];
            }
            String[] hexCodeLine = {symbolCode.get(i)[0], hexConvert, ""};
            hexCode.add(hexCodeLine);

            for (int j = 0; j < symbolCode.get(i).length; j++) {
                taSymbolCode.append(symbolCode.get(i)[j] + "   ");
            }
            taSymbolCode.append("\n");
        }

        String binaryConvert = null;
        for (int i = 0; i < hexCode.size(); i++) {
            binaryConvert = mtd.hexToBinary(hexCode.get(i)[1]);
            String[] binaryCodeLine = {mtd.hexToBinaryAdress(hexCode.get(i)[0]), binaryConvert, ""};
            binaryCode.add(binaryCodeLine);

            for (int j = 0; j < hexCode.get(i).length; j++) {
                taHexCode.append(hexCode.get(i)[j] + " ");
            }
            taHexCode.append("\n");
        }

        for (int i = 0; i < binaryCode.size(); i++) {
            for (int j = 0; j < binaryCode.get(i).length; j++) {
                taBinaryCode.append(binaryCode.get(i)[j] + "    ");
            }
            taBinaryCode.append("\n");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnDerleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerleActionPerformed
        // TODO add your handling code here:
        boolean hlt = false;
        int row = Integer.parseInt(_Grup_27_Command.PC, 2);
        for (int i = 0; i < symbolCode.size(); i++) {
            String[] memoryRow = new String[3];
            if (hlt == false) {
                String[] symbolRow = _Grup_27_FindSymbol.findSymbol(symbolCode.get(i)[1], symbolCode.get(i)[2]);
                memoryRow[0] = symbolRow[0];
                memoryRow[1] = symbolRow[1];
                memoryRow[2] = symbolRow[2];
                if (symbolCode.get(i)[1].contains("HLT")) {
                    hlt = true;
                }
            } else {
                memoryRow[0] = "0";
                memoryRow[1] = "0000";
                memoryRow[2] = symbolCode.get(i)[1];
            }

            tblMemory.setValueAt(memoryRow[0], row, 1);
            tblMemory.setValueAt(memoryRow[1], row, 2);
            tblMemory.setValueAt(memoryRow[2], row, 3);
            row++;
        }
    }//GEN-LAST:event_btnDerleActionPerformed
    private void btnCalistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalistirActionPerformed
        // TODO add your handling code here:   
        taMicroTable.setText("");
        _Grup_27_Command.AR = _Grup_27_Command.PC;
        lblAR.setText(_Grup_27_Command.AR);
        taMicroTable.append("FETCH \n");
        taMicroTable.append(" T0  AR <- PC \n");
        _Grup_27_Command.IR = (String) tblMemory.getValueAt(Integer.parseInt(_Grup_27_Command.AR, 2), 1) + ""
                + (String) tblMemory.getValueAt(Integer.parseInt(_Grup_27_Command.AR, 2), 2) + ""
                + (String) tblMemory.getValueAt(Integer.parseInt(_Grup_27_Command.AR, 2), 3);
        lblIR.setText(_Grup_27_Command.IR);
        taMicroTable.append(" T1  IR <- M[AR], PC <- PC + 1 \n");
        _Grup_27_RunSymbol.runSymbol(_Grup_27_Command.IR);
        _Grup_27_Command.nextPC();
    }//GEN-LAST:event_btnCalistirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String mif = "";
        for (int i = 0; i < hexCode.size(); i++) {
            mif = mif + hexCode.get(i)[1] + "\n";
        }
        File file = new File("dosya.mif");
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(_Grup_27_Anasayfa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        FileWriter fileWriter = null;
        try {
            fileWriter = new FileWriter(file, false);
        } catch (IOException ex) {
            Logger.getLogger(_Grup_27_Anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedWriter bWriter = new BufferedWriter(fileWriter);
        try {
            bWriter.write(mif);
        } catch (IOException ex) {
            Logger.getLogger(_Grup_27_Anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bWriter.close();
        } catch (IOException ex) {
            Logger.getLogger(_Grup_27_Anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_Grup_27_Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_Grup_27_Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_Grup_27_Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_Grup_27_Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _Grup_27_Anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCalistir;
    private javax.swing.JButton btnDerle;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JLabel lblAC;
    public static javax.swing.JLabel lblAR;
    public static javax.swing.JLabel lblDR;
    public static javax.swing.JLabel lblIR;
    public static javax.swing.JLabel lblPC;
    private javax.swing.JTextArea taAssamblyCode;
    private javax.swing.JTextArea taBinaryCode;
    private javax.swing.JTextArea taHexCode;
    private javax.swing.JTextArea taLabelTable;
    public static javax.swing.JTextArea taMicroTable;
    public static javax.swing.JTextArea taOutput;
    private javax.swing.JTextArea taSymbolCode;
    public static javax.swing.JTable tblMemory;
    // End of variables declaration//GEN-END:variables
}
